project_name: dysond

release:
  disable: false
  name_template: "{{.Tag}}"

before:
  hooks:
    - go mod tidy

builds:
  - main: ./dysond
    binary: dysond
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - LEDGER_ENABLED=true
    flags:
      - -trimpath
      - -mod=readonly
    tags:
      - netgo
      - ledger
    ldflags:
      - '-X github.com/cosmos/cosmos-sdk/version.Name=dysonprotocol'
      - '-X github.com/cosmos/cosmos-sdk/version.AppName=dysond'
      - '-X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}'
      - '-X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}'
      - '-X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"'
      - '-w'
      - '-s'
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - name_template: 'dysond-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'SHA256SUMS-{{ .Version }}.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\(.+\))??!?:.+$'
      order: 2
    - title: 'Other Changes'
      order: 999
