// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dysonprotocol/storage/module/v1/module.proto

package v1

import (
	_ "cosmossdk.io/depinject/appconfig/v1alpha1"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Module is the config object of the group module.
type Module struct {
	// max_execution_period defines the max duration after a proposal's voting
	// period ends that members can send a MsgExec to execute the proposal.
	MaxExecutionPeriod time.Duration `protobuf:"bytes,1,opt,name=max_execution_period,json=maxExecutionPeriod,proto3,stdduration" json:"max_execution_period"`
	// MaxMetadataLen defines the max chars allowed in all
	// messages that allows creating or updating a group
	// with a metadata field
	// Defaults to 255 if not explicitly set.
	MaxMetadataLen uint64 `protobuf:"varint,2,opt,name=max_metadata_len,json=maxMetadataLen,proto3" json:"max_metadata_len,omitempty"`
	// MaxProposalTitleLen defines the max chars allowed
	// in string for the MsgSubmitProposal and Proposal
	// summary field
	// Defaults to 255 if not explicitly set.
	MaxProposalTitleLen uint64 `protobuf:"varint,3,opt,name=max_proposal_title_len,json=maxProposalTitleLen,proto3" json:"max_proposal_title_len,omitempty"`
	// MaxProposalSummaryLen defines the max chars allowed
	// in string for the MsgSubmitProposal and Proposal
	// summary field
	// Defaults to 10200 if not explicitly set.
	MaxProposalSummaryLen uint64 `protobuf:"varint,4,opt,name=max_proposal_summary_len,json=maxProposalSummaryLen,proto3" json:"max_proposal_summary_len,omitempty"`
}

func (m *Module) Reset()         { *m = Module{} }
func (m *Module) String() string { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()    {}
func (*Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_fef0e31af736bdab, []int{0}
}
func (m *Module) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Module.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module.Merge(m, src)
}
func (m *Module) XXX_Size() int {
	return m.Size()
}
func (m *Module) XXX_DiscardUnknown() {
	xxx_messageInfo_Module.DiscardUnknown(m)
}

var xxx_messageInfo_Module proto.InternalMessageInfo

func (m *Module) GetMaxExecutionPeriod() time.Duration {
	if m != nil {
		return m.MaxExecutionPeriod
	}
	return 0
}

func (m *Module) GetMaxMetadataLen() uint64 {
	if m != nil {
		return m.MaxMetadataLen
	}
	return 0
}

func (m *Module) GetMaxProposalTitleLen() uint64 {
	if m != nil {
		return m.MaxProposalTitleLen
	}
	return 0
}

func (m *Module) GetMaxProposalSummaryLen() uint64 {
	if m != nil {
		return m.MaxProposalSummaryLen
	}
	return 0
}

func init() {
	proto.RegisterType((*Module)(nil), "dysonprotocol.storage.module.v1.Module")
}

func init() {
	proto.RegisterFile("dysonprotocol/storage/module/v1/module.proto", fileDescriptor_fef0e31af736bdab)
}

var fileDescriptor_fef0e31af736bdab = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x3f, 0x4b, 0xf3, 0x50,
	0x14, 0xc6, 0x73, 0xfb, 0x96, 0x0e, 0x79, 0x51, 0x34, 0x56, 0xa9, 0x15, 0xd3, 0xa2, 0x08, 0x45,
	0x24, 0x97, 0xda, 0x41, 0x70, 0x11, 0x8a, 0x6e, 0x2d, 0x94, 0xea, 0xd4, 0x25, 0x9c, 0x26, 0xd7,
	0x18, 0xc8, 0xcd, 0x09, 0xf9, 0x53, 0xd2, 0x6f, 0xe1, 0x24, 0xae, 0x6e, 0x8e, 0xce, 0x4e, 0x8e,
	0x1d, 0x3b, 0x8a, 0x83, 0x4a, 0x3b, 0xf8, 0x35, 0x24, 0xb7, 0xb7, 0x68, 0x16, 0x97, 0xcb, 0xb9,
	0xe7, 0xf9, 0x3d, 0xbf, 0xe5, 0xa8, 0x47, 0xf6, 0x38, 0x42, 0x3f, 0x08, 0x31, 0x46, 0x0b, 0x3d,
	0x1a, 0xc5, 0x18, 0x82, 0xc3, 0x28, 0x47, 0x3b, 0xf1, 0x18, 0x1d, 0x35, 0xe5, 0x64, 0x08, 0x42,
	0xab, 0xe5, 0x68, 0x43, 0xd2, 0x86, 0x64, 0x46, 0xcd, 0x6a, 0xdd, 0xc2, 0x88, 0x63, 0x44, 0x21,
	0x08, 0xe8, 0xa8, 0x09, 0x5e, 0x70, 0x03, 0x79, 0x45, 0xb5, 0xec, 0xa0, 0x83, 0x62, 0xa4, 0xd9,
	0x24, 0xb7, 0xba, 0x83, 0xe8, 0x78, 0x8c, 0x8a, 0xdf, 0x30, 0xb9, 0xa6, 0x76, 0x12, 0x42, 0xec,
	0xa2, 0x2f, 0xf3, 0x75, 0xe0, 0xae, 0x8f, 0x54, 0xbc, 0x8b, 0xd5, 0xde, 0x43, 0x41, 0x2d, 0x75,
	0x85, 0x59, 0x1b, 0xa8, 0x65, 0x0e, 0xa9, 0xc9, 0x52, 0x66, 0x25, 0x59, 0xc9, 0x0c, 0x58, 0xe8,
	0xa2, 0x5d, 0x21, 0x75, 0xd2, 0xf8, 0x7f, 0xbc, 0x6d, 0x2c, 0xe4, 0xc6, 0x52, 0x6e, 0x9c, 0x4b,
	0x79, 0x7b, 0x65, 0xf2, 0x5e, 0x53, 0xee, 0x3f, 0x6a, 0xe4, 0xf1, 0xeb, 0xe9, 0x90, 0xf4, 0x35,
	0x0e, 0xe9, 0xc5, 0x52, 0xd2, 0x13, 0x0e, 0xad, 0xa1, 0xae, 0x65, 0x6e, 0xce, 0x62, 0xb0, 0x21,
	0x06, 0xd3, 0x63, 0x7e, 0xa5, 0x50, 0x27, 0x8d, 0x62, 0x7f, 0x95, 0x43, 0xda, 0x95, 0xeb, 0x0e,
	0xf3, 0xb5, 0x96, 0xba, 0x95, 0x91, 0x41, 0x88, 0x01, 0x46, 0xe0, 0x99, 0xb1, 0x1b, 0x7b, 0x4c,
	0xf0, 0xff, 0x04, 0xbf, 0xc1, 0x21, 0xed, 0xc9, 0xf0, 0x2a, 0xcb, 0xb2, 0xd2, 0x89, 0x5a, 0xc9,
	0x95, 0xa2, 0x84, 0x73, 0x08, 0xc7, 0xa2, 0x56, 0x14, 0xb5, 0xcd, 0x5f, 0xb5, 0xcb, 0x45, 0xda,
	0x61, 0xfe, 0xe9, 0xfe, 0xf3, 0xcb, 0xdd, 0x1b, 0xd9, 0x55, 0x77, 0xf2, 0x27, 0xb1, 0x90, 0xd3,
	0x74, 0x79, 0xc6, 0xf6, 0xd9, 0x64, 0xa6, 0x93, 0xe9, 0x4c, 0x27, 0x9f, 0x33, 0x9d, 0xdc, 0xce,
	0x75, 0x65, 0x3a, 0xd7, 0x95, 0xd7, 0xb9, 0xae, 0x0c, 0x0e, 0xfe, 0xa8, 0xfd, 0x5c, 0x7f, 0x58,
	0x12, 0x44, 0xeb, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x71, 0x44, 0xca, 0x5b, 0x27, 0x02, 0x00, 0x00,
}

func (m *Module) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Module) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Module) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxProposalSummaryLen != 0 {
		i = encodeVarintModule(dAtA, i, uint64(m.MaxProposalSummaryLen))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxProposalTitleLen != 0 {
		i = encodeVarintModule(dAtA, i, uint64(m.MaxProposalTitleLen))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxMetadataLen != 0 {
		i = encodeVarintModule(dAtA, i, uint64(m.MaxMetadataLen))
		i--
		dAtA[i] = 0x10
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaxExecutionPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxExecutionPeriod):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintModule(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintModule(dAtA []byte, offset int, v uint64) int {
	offset -= sovModule(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Module) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxExecutionPeriod)
	n += 1 + l + sovModule(uint64(l))
	if m.MaxMetadataLen != 0 {
		n += 1 + sovModule(uint64(m.MaxMetadataLen))
	}
	if m.MaxProposalTitleLen != 0 {
		n += 1 + sovModule(uint64(m.MaxProposalTitleLen))
	}
	if m.MaxProposalSummaryLen != 0 {
		n += 1 + sovModule(uint64(m.MaxProposalSummaryLen))
	}
	return n
}

func sovModule(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozModule(x uint64) (n int) {
	return sovModule(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Module) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Module: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Module: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxExecutionPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthModule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthModule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaxExecutionPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMetadataLen", wireType)
			}
			m.MaxMetadataLen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMetadataLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxProposalTitleLen", wireType)
			}
			m.MaxProposalTitleLen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxProposalTitleLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxProposalSummaryLen", wireType)
			}
			m.MaxProposalSummaryLen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxProposalSummaryLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipModule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipModule(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowModule
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModule
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModule
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthModule
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupModule
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthModule
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthModule        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowModule          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupModule = fmt.Errorf("proto: unexpected end of group")
)
