// Since: cosmos-sdk 0.46

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dysonprotocol/script/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_ScriptInfo_FullMethodName  = "/dysonprotocol.script.v1.Query/ScriptInfo"
	Query_Web_FullMethodName         = "/dysonprotocol.script.v1.Query/Web"
	Query_EncodeJson_FullMethodName  = "/dysonprotocol.script.v1.Query/EncodeJson"
	Query_DecodeBytes_FullMethodName = "/dysonprotocol.script.v1.Query/DecodeBytes"
	Query_VerifyTx_FullMethodName    = "/dysonprotocol.script.v1.Query/VerifyTx"
	Query_Params_FullMethodName      = "/dysonprotocol.script.v1.Query/Params"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query is the dysonprotocol.script.v1 Query service.
type QueryClient interface {
	// ScriptInfo queries script info based on script address
	ScriptInfo(ctx context.Context, in *QueryScriptInfoRequest, opts ...grpc.CallOption) (*QueryScriptInfoResponse, error)
	// Queries the WSGI web application function of a script.
	Web(ctx context.Context, in *QueryWebRequest, opts ...grpc.CallOption) (*QueryWebResponse, error)
	// EncodeJson encodes a JSON string to bytes.
	EncodeJson(ctx context.Context, in *QueryEncodeJsonRequest, opts ...grpc.CallOption) (*QueryEncodeJsonResponse, error)
	// DecodeBytes decodes bytes to a JSON string.
	DecodeBytes(ctx context.Context, in *QueryDecodeBytesRequest, opts ...grpc.CallOption) (*QueryDecodeBytesResponse, error)
	// VerifyTx verifies a transaction.
	VerifyTx(ctx context.Context, in *QueryVerifyTxRequest, opts ...grpc.CallOption) (*QueryVerifyTxResponse, error)
	// Params queries the parameters of the script module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ScriptInfo(ctx context.Context, in *QueryScriptInfoRequest, opts ...grpc.CallOption) (*QueryScriptInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryScriptInfoResponse)
	err := c.cc.Invoke(ctx, Query_ScriptInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Web(ctx context.Context, in *QueryWebRequest, opts ...grpc.CallOption) (*QueryWebResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryWebResponse)
	err := c.cc.Invoke(ctx, Query_Web_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EncodeJson(ctx context.Context, in *QueryEncodeJsonRequest, opts ...grpc.CallOption) (*QueryEncodeJsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryEncodeJsonResponse)
	err := c.cc.Invoke(ctx, Query_EncodeJson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DecodeBytes(ctx context.Context, in *QueryDecodeBytesRequest, opts ...grpc.CallOption) (*QueryDecodeBytesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDecodeBytesResponse)
	err := c.cc.Invoke(ctx, Query_DecodeBytes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VerifyTx(ctx context.Context, in *QueryVerifyTxRequest, opts ...grpc.CallOption) (*QueryVerifyTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryVerifyTxResponse)
	err := c.cc.Invoke(ctx, Query_VerifyTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query is the dysonprotocol.script.v1 Query service.
type QueryServer interface {
	// ScriptInfo queries script info based on script address
	ScriptInfo(context.Context, *QueryScriptInfoRequest) (*QueryScriptInfoResponse, error)
	// Queries the WSGI web application function of a script.
	Web(context.Context, *QueryWebRequest) (*QueryWebResponse, error)
	// EncodeJson encodes a JSON string to bytes.
	EncodeJson(context.Context, *QueryEncodeJsonRequest) (*QueryEncodeJsonResponse, error)
	// DecodeBytes decodes bytes to a JSON string.
	DecodeBytes(context.Context, *QueryDecodeBytesRequest) (*QueryDecodeBytesResponse, error)
	// VerifyTx verifies a transaction.
	VerifyTx(context.Context, *QueryVerifyTxRequest) (*QueryVerifyTxResponse, error)
	// Params queries the parameters of the script module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) ScriptInfo(context.Context, *QueryScriptInfoRequest) (*QueryScriptInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScriptInfo not implemented")
}
func (UnimplementedQueryServer) Web(context.Context, *QueryWebRequest) (*QueryWebResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Web not implemented")
}
func (UnimplementedQueryServer) EncodeJson(context.Context, *QueryEncodeJsonRequest) (*QueryEncodeJsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncodeJson not implemented")
}
func (UnimplementedQueryServer) DecodeBytes(context.Context, *QueryDecodeBytesRequest) (*QueryDecodeBytesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecodeBytes not implemented")
}
func (UnimplementedQueryServer) VerifyTx(context.Context, *QueryVerifyTxRequest) (*QueryVerifyTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyTx not implemented")
}
func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call pancis, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_ScriptInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryScriptInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ScriptInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ScriptInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ScriptInfo(ctx, req.(*QueryScriptInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Web_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWebRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Web(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Web_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Web(ctx, req.(*QueryWebRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EncodeJson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEncodeJsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EncodeJson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_EncodeJson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EncodeJson(ctx, req.(*QueryEncodeJsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DecodeBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDecodeBytesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DecodeBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DecodeBytes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DecodeBytes(ctx, req.(*QueryDecodeBytesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VerifyTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVerifyTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VerifyTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_VerifyTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VerifyTx(ctx, req.(*QueryVerifyTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dysonprotocol.script.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScriptInfo",
			Handler:    _Query_ScriptInfo_Handler,
		},
		{
			MethodName: "Web",
			Handler:    _Query_Web_Handler,
		},
		{
			MethodName: "EncodeJson",
			Handler:    _Query_EncodeJson_Handler,
		},
		{
			MethodName: "DecodeBytes",
			Handler:    _Query_DecodeBytes_Handler,
		},
		{
			MethodName: "VerifyTx",
			Handler:    _Query_VerifyTx_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dysonprotocol/script/v1/query.proto",
}
